/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * DummyJSON API
 * DummyJSON API
 * OpenAPI spec version: 0.0.5
 */

export type GetProductsParams = {
  limit?: number;
  skip?: number;
  select?: string;
};
