/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * DummyJSON API
 * DummyJSON API
 * OpenAPI spec version: 0.0.5
 */
import type { Product } from './product';

export interface Products {
  limit?: number;
  products?: Product[];
  skip?: number;
  total?: number;
}
