/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * DummyJSON API
 * DummyJSON API
 * OpenAPI spec version: 0.0.5
 */

export type ProductDeleteAllOf = {
  deletedOn?: string;
  isDeleted?: boolean;
};
