/**
 * Generated by orval v6.23.0 🍺
 * Do not edit manually.
 * DummyJSON API
 * DummyJSON API
 * OpenAPI spec version: 0.0.5
 */
import type { Product } from './product';
import type { ProductDeleteAllOf } from './productDeleteAllOf';

export type ProductDelete = Product & ProductDeleteAllOf;
